targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**/*state.dart
            - lib/models/**/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/models/**/*.dart
        options:
          include_if_null: false
          explicit_to_json: true
          ignore_unannotated: false
