name: build app with workflow dispatch

on:
  workflow_dispatch:
    inputs:
      buildEnv:
        description: '実行するflavor'
        required: false
        default: 'dev'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, self-hosted ]
    runs-on: ${{ matrix.os }}
    env:
      slack_mention: 'TODO' #メンバーID
      flutter_channel: 'TODO'
      flutter_version: 'TODO'

    steps:
      ### setup ###
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - run: flutter pub get

      ### build ###
      - name: Android build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          ./scripts/buildAndroid.sh ${{ github.event.inputs.buildEnv }} 1.2.3 100

      - name: iOS build
        if: ${{ matrix.os == 'self-hosted' }}
        run: |
          ./scripts/buildiOS.sh ${{ github.event.inputs.buildEnv }} 1.2.3 100

      ### slack ###
      - name: action-slack
        uses: 8398a7/action-slack@v3
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          fields: repo,commit,job,took,workflow
          mention: ${{ env.slack_mention }}
          if_mention: always
          status: ${{ job.status }}
