name: Pull Requests

on:
  - pull_request

env:
  SLACK_MENTION: "UQ0KVAQ6T" #メンバーID # FIXME
  FLUTTER_CHANNEL: "stable" # FIXME
  FLUTTER_VERSION: "2.0.6" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter pub get

      ### Test ###
      - name: Test
        run: .github/workflows/scripts/test.sh

      - name: Codecov
        uses: codecov/codecov-action@v1
        continue-on-error: true
        timeout-minutes: 1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      ### Slack ###
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          fields: repo,commit,job,took,workflow
          mention: ${{ env.SLACK_MENTION }}
          if_mention: always
          status: ${{ job.status }}
