name: Pull Requests

on:
  - pull_request

env:
  FLUTTER_CHANNEL: "stable" # FIXME
  FLUTTER_VERSION: "2.5.2" # FIXME

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      ### Set up ###
      - uses: actions/checkout@v2

      - name: Flutter Cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_CHANNEL }}-${{ env.FLUTTER_VERSION }}

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter pub get

      ### Test ###
      - name: Test
        run: .github/workflows/scripts/test.sh

      - name: Codecov
        uses: codecov/codecov-action@v2
        continue-on-error: true
        timeout-minutes: 1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info

      ### Slack ###
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          fields: "all"
          mention: "channel"
          if_mention: "failure"
          status: ${{ job.status }}
